main:
  params: [date]
  steps:
    - log-start:
        call: sys.log
        args:
          text: "The EMD workflow has started."
          severity: "INFO"

    # Step 1: Get employee details
    - get-employee-details:
        call: http.get
        args:
          url: https://emd-transformation-de-462434857315.europe-west1.run.app/getvmmappingdata
          auth:
            type: OIDC
        result: employeeDetails

    - log-employee-details:
        call: sys.log
        args:
          data: ${employeeDetails.body}
          severity: "DEBUG"

    # Step 2: Get employee IDs
    - get-employee-ids:
        call: http.get
        args:
          url: https://emd-transformation-de-462434857315.europe-west1.run.app/employeesFromBigQuery?insertDate=${date}&transactionalId=90810ca7-a33e-4bd8-98f9-334cd8ec1c6f
          auth:
            type: OIDC
        result: employeeIds

    - log-employee-ids:
        call: sys.log
        args:
          data: ${employeeIds.body}
          severity: "DEBUG"

    - set-variables:
        assign:
          allEmployeeIds: ${employeeIds.body.employees}
          totalEmployees: ${len(employeeIds.body.employees)}
          batchSize: 10
          currentIndex: 0

    - log-total-employees:
        call: sys.log
        args:
          text: "Total employees to process: ${totalEmployees}"
          severity: "INFO"

    # Process employees in batches of 10
    - process-batches:
        switch:
          - condition: ${currentIndex < totalEmployees}
            next: process-current-batch
          - next: log-batch-complete

    - process-current-batch:
        assign:
          currentBatch: ${allEmployeeIds[currentIndex: (currentIndex + batchSize) > totalEmployees ? totalEmployees : (currentIndex + batchSize)]}

    - log-current-batch:
        call: sys.log
        args:
          text: "Processing batch: ${currentBatch}"
          severity: "DEBUG"

    - format-employee-ids:
        assign:
          formattedEmployeeIds: ${join(',', currentBatch)}

    - log-formatted-employee-ids:
        call: sys.log
        args:
          text: "Formatted Employee IDs: ${formattedEmployeeIds}"
          severity: "INFO"

    - process-employee-batch:
        call: http.post
        args:
          url: https://emd-transformation-de-462434857315.europe-west1.run.app/emdDataFromBigQuery?insertDate=${date}&transactionalId=90810ca7-a33e-4bd8-98f9-334cd8ec1c6f&employees=${formattedEmployeeIds}
          headers:
            Content-Type: "application/json"
          auth:
            type: OIDC
          body:
            empDetails: ${employeeDetails.body.mappingData}
        result: processResult

    - log-process-result:
        call: sys.log
        args:
          data: ${processResult}
          severity: "DEBUG"

    - increment-index:
        assign:
          currentIndex: ${currentIndex + batchSize}
        next: process-batches

    - log-batch-complete:
        call: sys.log
        args:
          text: "Batch processing completed."
          severity: "INFO"
